name: Generate GitHub Contribution Snake

on:
  # Atualiza automaticamente todos os dias
  schedule:
    - cron: "0 0 * * *"

  # Permite executar manualmente pelo GitHub
  workflow_dispatch:

  # Executa também quando houver alterações no repositório
  push:
    branches:
      - main

jobs:
  generate:

    permissions:
      contents: write

    runs-on: ubuntu-latest

    timeout-minutes: 5

    steps:

      # ==========================================
      # GERA A COBRINHA EM ROXO + PRETO
      # ==========================================
      - name: Generate GitHub Contribution Snake

        uses: Platane/snk/svg-only@v3

        with:

          # Seu usuário do GitHub
          github_user_name: nijige

          # Arquivos que serão gerados
          outputs: |

            # Versão principal
            dist/github-contribution-grid-snake.svg?color_snake=%238000FF&color_dots=%23000000,%231A0033,%23330066,%236600CC,%238000FF

            # Versão para modo escuro
            dist/github-contribution-grid-snake-dark.svg?color_snake=%23A855F7&color_dots=%23000000,%231A0033,%23330066,%237000D6,%23A855F7


      # ==========================================
      # PUBLICA OS ARQUIVOS NA BRANCH "OUTPUT"
      # ==========================================
      - name: Push Snake to Output Branch

        uses: crazy-max/ghaction-github-pages@v4

        with:
          target_branch: output
          build_dir: dist

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
